#!/usr/bin/env python3
import argparse
import sys
import dbus.exceptions


class MyParser(argparse.ArgumentParser):
    def error(self, message):
        sys.stderr.write('error: %s\n' % message)
        self.print_help()
        sys.exit(2)


if __name__ == "__main__":
    CONTROLLER_MODES = ['powersavelocked', 'powersave', 'stock', 'performance', 'performancelocked']
    try:
        bus = dbus.SystemBus()
        cpu_manager = bus.get_object("ee.ounapuu.BetterThermalDaemon", "/ee/ounapuu/BetterThermalDaemon")
    except dbus.exceptions.DBusException as e:
        print("Failed to initialize D-Bus object: '%s'" % str(e))
        sys.exit(2)

    parser = MyParser(argparse.ArgumentParser())
    parser.add_argument("mode",
                        help="Starts the GPU Manager Service in a given mode. Available modes: powersave, normal, performance",
                        type=str, nargs='?', default='normal')
    args = parser.parse_args()
    if args.mode in CONTROLLER_MODES:
        cpu_manager.set_mode(args.mode)
    else:
        # print("Invalid argument ", args.action)
        parser.error("Invalid argument " + str(args.action))
