#!/usr/bin/env python3

# Copyright (C) 2018 Herman Õunapuu
#
# This file is part of Better Thermal Daemon.
#
# Better Thermal Daemon is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Better Thermal Daemon is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Better Thermal Daemon.  If not, see <http://www.gnu.org/licenses/>.

import sys

import dbus.exceptions
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import GLib

from controller import BetterThermalDaemon

DBusGMainLoop(set_as_default=True)
loop = GLib.MainLoop()

# Declare a name where our service can be reached
try:
    bus_name = dbus.service.BusName("ee.ounapuu.BetterThermalDaemon",
                                    bus=dbus.SystemBus(),
                                    do_not_queue=True)
except dbus.exceptions.NameExistsException:
    print("service is already running")
    sys.exit(1)

# Run the loop
try:
    BetterThermalDaemon(bus_name)
    loop.run()
except KeyboardInterrupt:
    print("keyboard interrupt received")
except Exception as e:
    print("Unexpected exception occurred: '{}'".format(str(e)))
finally:
    loop.quit()
